name: "créer une application dans ArgoCD"
description: "créer une application dans ArgoCD si elle n'existe pas avec support Helm avancé et ignoreDifferences"

inputs:
  argocd_server:
    description: "URL du serveur Argo CD"
    required: true
  argocd_version:
    description: "La version d'argocd"
    default: "v2.10.20"
  argocd_username:
    description: "Nom d'utilisateur Argo CD"
    default: "admin"
  argocd_password:
    description: "Mot de passe de l'utilisateur Argo CD"
    required: true
  app_project_name:
    description: "Le nom du projet où l'application sera déployée"
    required: true
  app_name:
    description: "Le nom de l'application"
    required: true
  app_dest_namespace: 
    description: "Espace de destination du projet Argo CD"
    default: "defaultApp"
  app_manifest_repo:
    description: "URL du dépôt Git pour le manifeste de l'application"
    required: true
  app_manifest_repo_branch:
    description: "Récupérer la branche du dépôt Git pour le manifeste de l'application"
    default: "main"
  app_manifest_path:
    description: "Chemin du manifeste de l'application"
    required: true
  helm_params:
    description: 'La liste de parametres helm avec le format "key1=val1,key2=val2"'
    default: ''
  helm_value_files:
    description: "Liste des fichiers de valeurs Helm (séparés par des virgules)"
    default: ""
  sync_options:
    description: "Options de synchronisation (ex: CreateNamespace=true,RespectIgnoreDifferences=true)"
    default: ""
  ignore_differences:
    description: "Structure JSON pour ignoreDifferences (ex: '[{\"kind\":\"Secret\",\"name\":\"my-secret\",\"jqPathExpressions\":[\".data\"]}]')"
    default: "[]"
  private_repo:
    description: 'Le repo précise si le repo est privé ou public'
    default: 'false'
  github_app_id:
    required: false
  github_app_installation_id:
    required: false
  github_app_private_key:
    required: false

runs:
  using: "composite"
  steps:    
    - name: Vérifier et installer ArgoCD CLI
      shell: bash    
      run: |
        if ! command -v argocd &> /dev/null; then
            wget https://github.com/argoproj/argo-cd/releases/download/${{inputs.argocd_version}}/argocd-linux-amd64
            sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
            rm argocd-linux-amd64
        fi
        argocd version --client

    - name: Login au Argo CD
      shell: bash
      run: |  
        argocd login ${{ inputs.argocd_server }} --username ${{ inputs.argocd_username }} --password "${{ inputs.argocd_password }}" --grpc-web --insecure
    
    - name: Ajouter le repo Git dans Argo CD (GitHub App) si privé
      if: inputs.private_repo == 'true'
      shell: bash
      run: |
        if ! argocd repo list | grep -q "${{ inputs.app_manifest_repo }}"; then
          PRIVATE_KEY_FILE="$(mktemp)"
          printf '%s' "${{ inputs.github_app_private_key }}" > "$PRIVATE_KEY_FILE"
          argocd repo add "${{ inputs.app_manifest_repo }}" \
            --github-app-id "${{ inputs.github_app_id }}" \
            --github-app-installation-id "${{ inputs.github_app_installation_id }}" \
            --github-app-private-key-path "$PRIVATE_KEY_FILE" \
            --grpc-web --insecure
          rm -f "$PRIVATE_KEY_FILE"
        fi

    - name: Check si le projet Argo CD existe
      id: check_project
      continue-on-error: true
      shell: bash
      run: |
        if argocd proj get ${{ inputs.app_project_name }}; then
          echo "project_exists=true" >> $GITHUB_OUTPUT
        else
          echo "project_exists=false" >> $GITHUB_OUTPUT
        fi 
    
    - name: Quitter si le projet n'existe pas
      shell: bash
      run: |
        if [ "${{ steps.check_project.outputs.project_exists }}" == "false" ]; then
          echo "Projet ${{inputs.app_project_name}} n'existe pas. Arret."
          exit 1
        fi

    - name: Créer ou mettre à jour l'application Argo CD
      shell: bash
      run: |
        if ! argocd app get ${{inputs.app_name}} &> /dev/null; then   
          echo "L'application '${{inputs.app_name}}' n'existe pas. Création..."
          
          # Construction de la commande de base
          CMD="argocd app create ${{inputs.app_name}} \
            --repo ${{inputs.app_manifest_repo}} \
            --revision ${{ inputs.app_manifest_repo_branch }} \
            --path ${{inputs.app_manifest_path}} \
            --dest-namespace ${{inputs.app_dest_namespace}} \
            --dest-server https://kubernetes.default.svc \
            --project ${{ inputs.app_project_name }} \
            --sync-policy automated \
            --grpc-web --insecure"

          IFS=',' read -ra S_OPTS <<< "${{ inputs.sync_options }}"
          for opt in "${S_OPTS[@]}"; do
            CMD="$CMD --sync-option $opt"
          done

          if [ -n "${{ inputs.helm_params }}" ]; then
            IFS=',' read -ra H_PARAMS <<< "${{ inputs.helm_params }}"
            for param in "${H_PARAMS[@]}"; do
              CMD="$CMD --helm-set $param"
            done
          fi

          IFS=',' read -ra V_FILES <<< "${{ inputs.helm_value_files }}"
          for vfile in "${V_FILES[@]}"; do
            CMD="$CMD --values $vfile"
          done

          echo "Exécution : $CMD"
          $CMD
        else
          echo "L'application existe déjà. On passe à la phase de mise à jour/patch."
        fi

    - name: Appliquer les correctifs (IgnoreDifferences & SyncOptions)
      shell: bash
      run: |
        # On utilise Patch pour les structures complexes que 'create' gère mal via CLI
        # 1. Mise à jour de ignoreDifferences si fourni
        if [ "${{ inputs.ignore_differences }}" != "[]" ]; then
          echo "Application du patch ignoreDifferences..."
          argocd app patch ${{ inputs.app_name }} \
            --patch "{\"spec\": {\"ignoreDifferences\": ${{ inputs.ignore_differences }} }}" \
            --type merge --grpc-web --insecure
        fi

    - name: Assert Argo CD Application Health
      shell: bash
      run: argocd app wait ${{ inputs.app_name}} --health --timeout 300