name: "créer une application dans ArgoCD"
description: "créer une application dans ArgoCD si elle n'existe pas"

inputs:
  role_to_assume:
    description: "Nom du rôle AWS"
    required: true
  aws_region:
    description: "Région AWS"
    required: true
    default: "ca-central-1"
  argocd_server:
    description: "URL du serveur Argo CD"
    required: true
  argocd_username:
    description: "Nom d'utilisateur Argo CD"
    default: "admin"
  secret_manager_secret_id:
    description: "ID du secret dans Secrets Manager"
    required: true
  app-name:
    description: "Le nom de l'application"
    required: true
  app_dest_amespace: 
    description: "Espace de destination du projet Argo CD"
    required: true
  app_manifest_repo:
    description: "URL du dépôt Git pour le manifeste de l'application"
    required: true
  app_manifest_repo_branch:
    description: "Récupérer la branche du dépôt Git pour le manifeste de l'application"
    default: "main"
  app_manifest_path:
    description: "Chemin du manifeste de l'application"
    required: true

runs:
  using: "composite"
  steps:

    # Secrets manager pour le mdp de l'admin d'ArgoCD

    - name: Checkout code
      uses: actions/checkout@v3        

    - name: "Configure AWS credentials for role ${{ inputs.role_to_assume }}"
      uses: aws-actions/configure-aws-credentials@v4          
      with:                
        role-to-assume: ${{ inputs.role_to_assume }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ inputs.aws_region }}

    - name: Obtenir le secret du mdp de l'admin d'ArgoCD dans secretsmanager
      id: secretsmanager
      uses: aws-actions/aws-secretsmanager-get-secrets@v1 
      with:
        secret-ids: |
          ARGOCD_ADM_CREDS,${{ inputs.secret_manager_secret_id }}
        #name or ARN of the secret
        parse-json-secrets: true # Set to true if your secret value is JSON

    - name: Verify secret existence ADMINPASSWORD
      shell: bash    
      run: |
        if [ -z "${{ env.ARGOCD_ADM_CREDS_ADMINPASSWORD }}" ]; then
          echo "Error: Secret ${{ inputs.secret_manager_secret_id}} or its key 'ADMINPASSWORD' not found in AWS Secrets Manager."
          exit 1
        else
          echo "Secret ${{ inputs.secret_manager_secret_id}} exists and is available."
        fi    

    # ArgoCD applcation

    - name: Vérifier et installer ArgoCD CLI
      shell: bash    
      run: |
        if ! command -v argocd &> /dev/null
        then
            echo "ArgoCD CLI not found, installing..."
            # Download the latest ArgoCD CLI for Linux AMD64
            # You can find the latest version from https://github.com/argoproj/argo-cd/releases/latest
            LATEST_VERSION=$(curl -s https://api.github.com/repos/argoproj/argo-cd/releases/latest | grep "tag_name" | cut -d : -f 2,3 | tr -d \" | tr -d , | awk '{print $1}')
            wget https://github.com/argoproj/argo-cd/releases/download/${LATEST_VERSION}/argocd-linux-amd64
            sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
            rm argocd-linux-amd64
            echo "ArgoCD CLI installed."
        else
            echo "ArgoCD CLI is already installed."
        fi
        argocd version --client # Verify installation

    - name: Login au Argo CD
      shell: bash
      run: |  
        argocd login ${{ inputs.argocd_server }} --username ${{ inputs.argocd_username }} --password ${{ env.ARGOCD_ADM_CREDS_ADMINPASSWORD }} --grpc-web --insecure

    - name: Check si le projet Argo CD existe
      id: check_project
      continue-on-error: true # This ensures the step won't fail the workflow if the command errors
      shell: bash
      run: |
        # if argocd proj get ${{ inputs.app-name }}; then
        #   echo "project_exists=true" >> $GITHUB_OUTPUT
        # else
        #   echo "project_exists=false" >> $GITHUB_OUTPUT
        # fi
        # Attempt to get the project and capture the exit code
        argocd proj get ${{ inputs.app-name }} &> /dev/null
        echo "exit_code=$?" >> $GITHUB_OUTPUT        
      
    - name: Create Argo CD project if it doesn't exist
      shell: bash
      #if: steps.check_project.outputs.project_exists == 'false'        
      #if: steps.check_project.outputs.exit_code != '0' #project doesn't exist
      #if: failure() # previous step failed
      #if: ${{ failure() }} # This step runs only if previous step failed
      run: |
          echo "project does not exist. Will be created."        
          argocd app create ${{ inputs.app-name }} \
          --repo ${{ inputs.app_manifest_repo }} \
          --revision ${{ inputs.app_manifest_repo_branch }} \
          --path ${{ inputs.app_manifest_path }} \
          --dest-namespace ${{ inputs.app_dest_amespace }} \
          --dest-server https://kubernetes.default.svc \
          --directory-recurse \
          --upsert \
          --grpc-web
          # --sync-policy automatic 


    - name: Assert Argo CD Application Health
      shell: bash
      run: echo "final step, value of exit_code ${{ steps.check_project.outputs.exit_code }} project ${{ inputs.app-name }} should have been created"  

    # - name: Assert Argo CD Application Health
    #   shell: bash
    #   run: argocd app wait ${{ inputs.app-name}} --health --timeout 300        