name: "Publier une image au registre des conteneurs d'images"
description: "Publier une image Docker aux registry (GitHub Packages)"
inputs:
  registry:
    description: "Le registre où publier l'image produite"
    required: true
    default: ghcr.io
  image-name:
    description: "Le nom de l'image à produire"
    required: true
    default: ${{ github.repository }}
  github-token:
    description: "Le token pour se logger au registre des conteneurs d'images"
    required: true
    default: "devCqen"

permissions:

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Log in au registre de conteneurs d'images
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract metadata (tags, labels) pour Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{inputs.registry}}/${{inputs.image-name}}

    - name: Build et push de l'image Docker
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }} 

    - name: Générer le certificat de l'artefact
      # seulement si le repository est public
      if: github.repository_visibility == 'public' # cette condition est nécessaire pour éviter les erreurs de publication dans les repositories privés
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{inputs.registry}}/${{inputs.image-name}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true                     
