---
- name: Create or update Aurora PostgreSQL databases, users and secrets
  hosts: local
  gather_facts: false

  collections:
    - mcn_cqen.infrastructure

  vars:
    ansible_python_interpreter: "{{ lookup('env', 'PYTHON_BIN') }}"
    pg_login:
      login_host: "{{ db_host }}"
      login_port: "{{ db_port }}"
      login_user: "{{ db_master_user }}"
      login_password: "{{ db_master_password }}"
      ssl_mode: require

  roles:
    - role: aurora_users
      vars_files:
        - "group_vars/all.yml"
        - "group_vars/apps.yml"
        - "group_vars/roles.yml"
